train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data_resample
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 16
      scale_max: 16
      augment: false
      sample_q: 256
  batch_size: 64
val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: ./data_val
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 16
      scale_max: 16
      sample_q: 256
  batch_size: 64
data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: lte
  args:
    encoder_spec:
      name: swinir
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 3
        hidden_list:
        - 256
        - 256
        - 256
    hidden_dim: 256
optimizer:
  name: adam
  args:
    lr: 0.0002
epoch_max: 1000
multi_step_lr:
  milestones:
  - 500
  - 800
  - 900
  - 950
  gamma: 0.5
epoch_val: 1
epoch_save: 100
resume: ./save/_train_swinir-lte/epoch-last.pth
